%  LaTeX support: latex@mdpi.com
%  For support, please attach all files needed for compiling as well as the log file, and specify your operating system, LaTeX version, and LaTeX editor.

%=================================================================
% pandoc conditionals added to preserve backwards compatibility with previous versions of rticles

\documentclass[,,,,pdftex]{Definitions/mdpi}


%% Some pieces required from the pandoc template
\setlist[itemize]{leftmargin=*,labelsep=5.8mm}
\setlist[enumerate]{leftmargin=*,labelsep=4.9mm}


%--------------------
% Class Options:
%--------------------

%---------
% article
%---------
% The default type of manuscript is "article", but can be replaced by:
% abstract, addendum, article, book, bookreview, briefreport, casereport, comment, commentary, communication, conferenceproceedings, correction, conferencereport, entry, expressionofconcern, extendedabstract, datadescriptor, editorial, essay, erratum, hypothesis, interestingimage, obituary, opinion, projectreport, reply, retraction, review, perspective, protocol, shortnote, studyprotocol, systematicreview, supfile, technicalnote, viewpoint, guidelines, registeredreport, tutorial
% supfile = supplementary materials

%----------
% submit
%----------
% The class option "submit" will be changed to "accept" by the Editorial Office when the paper is accepted. This will only make changes to the frontpage (e.g., the logo of the journal will get visible), the headings, and the copyright information. Also, line numbering will be removed. Journal info and pagination for accepted papers will also be assigned by the Editorial Office.

%------------------
% moreauthors
%------------------
% If there is only one author the class option oneauthor should be used. Otherwise use the class option moreauthors.

%---------
% pdftex
%---------
% The option pdftex is for use with pdfLaTeX. Remove "pdftex" for (1) compiling with LaTeX & dvi2pdf (if eps figures are used) or for (2) compiling with XeLaTeX.

%=================================================================
% MDPI internal commands - do not modify
\firstpage{1}
\makeatletter
\setcounter{page}{\@firstpage}
\makeatother
\pubvolume{1}
\issuenum{1}
\articlenumber{0}
\pubyear{2023}
\copyrightyear{2023}
%\externaleditor{Academic Editor: Firstname Lastname}
\datereceived{ }
\daterevised{ } % Comment out if no revised date
\dateaccepted{ }
\datepublished{ }
%\datecorrected{} % For corrected papers: "Corrected: XXX" date in the original paper.
%\dateretracted{} % For corrected papers: "Retracted: XXX" date in the original paper.
\hreflink{https://doi.org/} % If needed use \linebreak
%\doinum{}
%\pdfoutput=1 % Uncommented for upload to arXiv.org

%=================================================================
% Add packages and commands here. The following packages are loaded in our class file: fontenc, inputenc, calc, indentfirst, fancyhdr, graphicx, epstopdf, lastpage, ifthen, float, amsmath, amssymb, lineno, setspace, enumitem, mathpazo, booktabs, titlesec, etoolbox, tabto, xcolor, colortbl, soul, multirow, microtype, tikz, totcount, changepage, attrib, upgreek, array, tabularx, pbox, ragged2e, tocloft, marginnote, marginfix, enotez, amsthm, natbib, hyperref, cleveref, scrextend, url, geometry, newfloat, caption, draftwatermark, seqsplit
% cleveref: load \crefname definitions after \begin{document}

%=================================================================
% Please use the following mathematics environments: Theorem, Lemma, Corollary, Proposition, Characterization, Property, Problem, Example, ExamplesandDefinitions, Hypothesis, Remark, Definition, Notation, Assumption
%% For proofs, please use the proof environment (the amsthm package is loaded by the MDPI class).

%=================================================================
% Full title of the paper (Capitalized)
\Title{ProyectoAED2024}

% MDPI internal command: Title for citation in the left column
\TitleCitation{ProyectoAED2024}

% Author Orchid ID: enter ID or remove command
%\newcommand{\orcidauthorA}{0000-0000-0000-000X} % Add \orcidA{} behind the author's name
%\newcommand{\orcidauthorB}{0000-0000-0000-000X} % Add \orcidB{} behind the author's name


% Authors, for the paper (add full first names)
\Author{}


%\longauthorlist{yes}


% MDPI internal command: Authors, for metadata in PDF
\AuthorNames{}

% MDPI internal command: Authors, for citation in the left column
%\AuthorCitation{Lastname, F.; Lastname, F.; Lastname, F.}
% If this is a Chicago style journal: Lastname, Firstname, Firstname Lastname, and Firstname Lastname.
\AuthorCitation{Albacete, L; Ribes, C; Pedro, J.}

% Affiliations / Addresses (Add [1] after \address if there is only one affiliation.)
\address{%
$^{1}$ \quad Universitat de València.
ETSE.; \href{mailto:alcaluis@alumni.uv.es}{\nolinkurl{alcaluis@alumni.uv.es}}\\
$^{2}$ \quad Universitat de València.
ETSE.; \href{mailto:carigar4@alumni.uv.es}{\nolinkurl{carigar4@alumni.uv.es}}\\
$^{3}$ \quad Universitat de València.
ETSE.; \href{mailto:jopebrui@alumni.uv.es}{\nolinkurl{jopebrui@alumni.uv.es}}\\
}

% Contact information of the corresponding author
\corres{Correspondence: }

% Current address and/or shared authorship








% The commands \thirdnote{} till \eighthnote{} are available for further notes

% Simple summary
\simplesumm{Estudio de los delitos causados por menores en España entre
2013 y 2023.}

%\conference{} % An extended version of a conference paper

% Abstract (Do not insert blank lines, i.e. \\)
\abstract{Proyecto de tratamiento de datos para la asignatura de
Análisis exploratorio de datos. El tópico es la delincuencia en España
provocado por menores de entre 14 y 17 años (ambos inclusives). Donde se
estudiarán los delitos causados con mayor frecuencia.}


% Keywords
\keyword{Delito; Delincuencia; Menores; Datos; Ciencia de Datos;}

% The fields PACS, MSC, and JEL may be left empty or commented out if not applicable
%\PACS{J0101}
%\MSC{}
%\JEL{}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Diversity
%\LSID{\url{http://}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Applied Sciences

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Data



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Toxins


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Encyclopedia


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Only for the journal Advances in Respiratory Medicine
%\addhighlights{yes}
%\renewcommand{\addhighlights}{%

%\noindent This is an obligatory section in “Advances in Respiratory Medicine”, whose goal is to increase the discoverability and readability of the article via search engines and other scholars. Highlights should not be a copy of the abstract, but a simple text allowing the reader to quickly and simplified find out what the article is about and what can be cited from it. Each of these parts should be devoted up to 2~bullet points.\vspace{3pt}\\
%\textbf{What are the main findings?}
% \begin{itemize}[labelsep=2.5mm,topsep=-3pt]
% \item First bullet.
% \item Second bullet.
% \end{itemize}\vspace{3pt}
%\textbf{What is the implication of the main finding?}
% \begin{itemize}[labelsep=2.5mm,topsep=-3pt]
% \item First bullet.
% \item Second bullet.
% \end{itemize}
%}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Pandoc syntax highlighting
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}

% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



\usepackage{longtable}

\begin{document}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Introducción}\label{introducciuxf3n}

\subsection{Definición proyecto y planteamiento de preguntas
(objetivos)}\label{definiciuxf3n-proyecto-y-planteamiento-de-preguntas-objetivos}

La delincuencia en España es un tema de conversación latente. Aunque no
lo es tanto, pero sigue siendo importante, es hablar de la edad del
delincuente. En este estudio analizaremos los diferentes tipos de delito
ocasionados por menores de entre 14 y 17 años durante los 10 últimos
años. Los objetivos del estudio es responder a las siguientes preguntas:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  ¿Cuáles son los delitos más frecuentes y que edades lo frecuentan?
  ¿Siguen siendo recientes o han disminuido?
\item
  Analizar los picos de delitos y relacionarlos con hechos reales.
  (Buscar sucesos, leyes)
\item
  Encontrar tendencias entre los años.
\item
  \ldots{}
\end{enumerate}

WIP: Definir el problema y los objetivos del estudio

\subsection{Carga de librerías y
datos}\label{carga-de-libreruxedas-y-datos}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Carga de librerias}
\NormalTok{librerias }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"readr"}\NormalTok{,       }\CommentTok{\# Lectura de ficheros con formato}
               \StringTok{"dplyr"}\NormalTok{,       }\CommentTok{\# Gramática de manipulación de datos}
               \StringTok{"ggplot2"}\NormalTok{)     }\CommentTok{\# Visualización mediante gráficas elegantes}
\NormalTok{pacman}\SpecialCharTok{::}\FunctionTok{p\_load}\NormalTok{(}\AttributeTok{char=}\NormalTok{librerias)}

\CommentTok{\# Carga de datos}
\NormalTok{col\_names }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"delitos\_n1"}\NormalTok{, }\StringTok{"delitos\_n2"}\NormalTok{, }\StringTok{"delitos\_n3"}\NormalTok{,}
               \StringTok{"delitos\_n4"}\NormalTok{, }\StringTok{"delitos\_n5"}\NormalTok{, }\StringTok{"edad"}\NormalTok{,}
               \StringTok{"año"}\NormalTok{, }\StringTok{"total\_delitos"}\NormalTok{)}

\NormalTok{delitos\_menores\_raw }\OtherTok{\textless{}{-}} \FunctionTok{read\_delim}\NormalTok{(}
  \AttributeTok{file =} \StringTok{"../data/delitos\_menores\_2013\_2023.csv"}\NormalTok{, }
  \AttributeTok{delim =} \StringTok{";"}\NormalTok{,}
  \AttributeTok{escape\_double =} \ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{trim\_ws =} \ConstantTok{TRUE}\NormalTok{,                        }\CommentTok{\# Espacios y tabulaciones eliminados.}
  \AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{,                }\CommentTok{\# Omitir mensajes en carga de datos.}
  \AttributeTok{col\_names =}\NormalTok{ col\_names,                 }\CommentTok{\# Si proporcionamos nombres de columnas hemos de}
                                         \CommentTok{\# saltarnos la primera fila (skip=1).}
  \AttributeTok{skip =} \DecValTok{1}\NormalTok{,}
  \AttributeTok{locale =} \FunctionTok{locale}\NormalTok{(}\AttributeTok{grouping\_mark =} \StringTok{"."}\NormalTok{))  }\CommentTok{\# Locale nos permitirá leer debidamente}
                                         \CommentTok{\# los millares.}
\end{Highlighting}
\end{Shaded}

\subsection{Estudio y acondicionamiento de los
datos}\label{estudio-y-acondicionamiento-de-los-datos}

WIP (TODOS, \#01-Introduccion): - Análisis de la estructura y valores
iniciales de los datos. - Acondicionamiento y preparación de los datos.
- Validación datos acondicionados

\subsubsection{Análisis de la estructura y valores iniciales de los
datos.}\label{anuxe1lisis-de-la-estructura-y-valores-iniciales-de-los-datos.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Análisis de la estructura y valores iniciales de los datos.}
\FunctionTok{summary}\NormalTok{(delitos\_menores\_raw)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   delitos_n1         delitos_n2         delitos_n3         delitos_n4       
##  Length:2915        Length:2915        Length:2915        Length:2915       
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##   delitos_n5            edad                año      total_delitos    
##  Length:2915        Length:2915        Min.   :2013   Min.   :    0.0  
##  Class :character   Class :character   1st Qu.:2015   1st Qu.:   17.0  
##  Mode  :character   Mode  :character   Median :2018   Median :   78.0  
##                                        Mean   :2018   Mean   :  756.2  
##                                        3rd Qu.:2021   3rd Qu.:  410.0  
##                                        Max.   :2023   Max.   :26349.0  
##                                                       NA's   :210
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# str(delitos\_menores\_raw)     \# STR no nos aporta información adicional}
\CommentTok{\# glimpse(delitos\_menores\_raw) \# Lo mismo sucede con GLIMPSE}
\end{Highlighting}
\end{Shaded}

Gracias a ``summary'' podemos apreciar qué columnas contienen NAs y si
los valores (de las columnas numéricas) entran dentro de lo esperado
(min, max, median, \ldots).

Teniendo para la columna \textbf{año} valores esperados, desde 2013
hasta 2023 y la media obviamente en 2018. Respecto a la columna
\textbf{total\_delitos}, podemos apreciar que tiene un número relevante
de valores faltantes (210) y confirmamos que los valores se han
importado correctamente (manteniendo los millares).

Además hemos identificado que la columna \textbf{edad} se ha importado
como tipo ``character''. Tras hacer una visualización del archivo nos
damos cuenta que los años se han importado como ``14 años'' agregando el
sustantivo para todos los valores y en algunos casos agregando un
``Total''. Acondicionamiento de la columna será necesario.

Las columnas restantes, que son de tipo ``character'', representan el
delito en sus distintos niveles. Habremos de factorizar estas variable
categóricas.

El uso de la función ``str'' o ``glimpse'' en este caso no nos ha
aportado información adicional.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 1. delitos\_n1}
\FunctionTok{table}\NormalTok{(delitos\_menores\_raw}\SpecialCharTok{$}\NormalTok{delitos\_n1, }\AttributeTok{useNA =} \StringTok{"always"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Total Infracciones               <NA> 
##               2915                  0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 2. delitos\_n2}
\FunctionTok{table}\NormalTok{(delitos\_menores\_raw}\SpecialCharTok{$}\NormalTok{delitos\_n2, }\AttributeTok{useNA =} \StringTok{"always"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## A Delitos  B Faltas      <NA> 
##      2585       275        55
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 3. delitos\_n3, N4, N5}
\FunctionTok{tail}\NormalTok{(}\FunctionTok{table}\NormalTok{(delitos\_menores\_raw}\SpecialCharTok{$}\NormalTok{delitos\_n3, }\AttributeTok{useNA =} \StringTok{"always"}\NormalTok{), }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## R Resto de delitos               <NA> 
##                 55                165
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tail}\NormalTok{(}\FunctionTok{table}\NormalTok{(delitos\_menores\_raw}\SpecialCharTok{$}\NormalTok{delitos\_n4, }\AttributeTok{useNA =} \StringTok{"always"}\NormalTok{), }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 8.99 Otros delitos contra la libertad e indemnidad sexuales 
##                                                          55 
##                                                        <NA> 
##                                                        1045
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tail}\NormalTok{(}\FunctionTok{table}\NormalTok{(delitos\_menores\_raw}\SpecialCharTok{$}\NormalTok{delitos\_n5, }\AttributeTok{useNA =} \StringTok{"always"}\NormalTok{), }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 22.2.2 Resistencia y desobediencia                               <NA> 
##                                 55                               2695
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 4. edad}
\FunctionTok{table}\NormalTok{(delitos\_menores\_raw}\SpecialCharTok{$}\NormalTok{edad, }\AttributeTok{useNA =} \StringTok{"always"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 14 años 15 años 16 años 17 años    Total     <NA> 
##      583      583      583      583      583        0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 5. año}
\FunctionTok{table}\NormalTok{(delitos\_menores\_raw}\SpecialCharTok{$}\NormalTok{año, }\AttributeTok{useNA =} \StringTok{"always"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 <NA> 
##  265  265  265  265  265  265  265  265  265  265  265    0
\end{verbatim}

De las diferentes columnas podemos decir que:

\begin{itemize}
\tightlist
\item
  \textbf{delitos\_n1}: la primera columna no nos aporta valor alguno al
  solo tener un valor. Más adelante será eliminada.
\item
  \textbf{delitos\_n2}: esta columna nos servirá para hacer el primer
  filtrado y quedarnos con solo los delitos y faltas cometidas.
  Omitiendo los totales calculados. Sus valores pueden ser reemplazados
  en valores más claros.
\item
  \textbf{delitos\_n3, n4, y n5}: ayudan a clasificar los delitos en
  subtipos de infracción. Sin embargo, podemos ver como a mayor nivel de
  detalle más valores faltantes. Esto se debe a que un nivel de
  clasificación tan preciso no es necesario para describir todos los
  delitos.
\end{itemize}

La columna \textbf{delitos\_n5} no será necesaria. Aporta muy poca
información y el análisis no requerirá tanto nivel de detalle para una
infracción.

\begin{itemize}
\tightlist
\item
  \textbf{edad}: todos los datos de esta columna son uniformes y
  esperados (ningún valor faltante). Finalmente se eliminarán aquellas
  instancias que representen un total y se convertirá la columna a tipo
  numérico.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 6. total\_delitos}
\NormalTok{df\_total\_delitos }\OtherTok{\textless{}{-}}\NormalTok{ delitos\_menores\_raw }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\FunctionTok{startsWith}\NormalTok{(delitos\_n3, }\StringTok{"13"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(edad}\SpecialCharTok{==}\StringTok{"14 años"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(año}\SpecialCharTok{==}\DecValTok{2013}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{delitos\_n4 =} \FunctionTok{ifelse}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(delitos\_n4),}
                             \FunctionTok{substring}\NormalTok{(delitos\_n4, }\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{),}
                             \ConstantTok{NA}\NormalTok{))}

\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(df\_total\_delitos[}\FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{8}\NormalTok{)], }\AttributeTok{format =} \StringTok{"latex"}\NormalTok{, }
             \AttributeTok{booktabs =} \ConstantTok{TRUE}\NormalTok{, }
             \AttributeTok{caption =} \StringTok{"Caso delitos \textquotesingle{}Contra el patrimonio y el orden }
\StringTok{                        socioeconómico\textquotesingle{} en 2013 por delincuentes de 14 años"}\NormalTok{, }
             \AttributeTok{align =} \StringTok{\textquotesingle{}lll\textquotesingle{}}\NormalTok{, }\AttributeTok{centering =} \ConstantTok{TRUE}\NormalTok{,}
             \AttributeTok{table.envir =} \StringTok{"table"}\NormalTok{, }\AttributeTok{position =} \StringTok{"H"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[H]

\caption{\label{tab:intro_analisis_inicial_3}Caso delitos 'Contra el patrimonio y el orden 
                        socioeconómico' en 2013 por delincuentes de 14 años}
\centering
\begin{tabular}[t]{lll}
\toprule
delitos\_n4 & delitos\_n5 & total\_delitos\\
\midrule
NA & NA & 1433\\
13.1 & NA & 142\\
13.2 & NA & 1108\\
13.2 & 13.2.1 Robo con violencia & 602\\
13.2 & 13.2.2 Robo con fuerza & 506\\
\addlinespace
13.4 & NA & 55\\
13.5 & NA & 9\\
13.6 & NA & 8\\
13.9 & NA & 97\\
13.1 & NA & 13\\
\addlinespace
13.9 & NA & 1\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  \textbf{total}: respecto a esta columna pese a que no hayamos
  utilizado ninguna instrucción, hemos mediante visualización del
  fichero analizado un caso en concreto para definir la naturaleza de
  esta columna. Ya vimos anteriormente, gracias a otras columnas, que
  hay agrupaciones internas de los datos calculando los totales. Pero
  eso no es todo. Podemos apreciar que el total de un delito, es la suma
  de todas sus subclasificaciones.
\end{itemize}

Es decir, el total de ``13.2 Robos'', es igual a la suma de ``13.2.1'' y
``13.2.2'', a su vez el delito contra el patrimonio es la suma de los
delitos ``13.1'', ``13.2'', \ldots{} Este hecho agrega redundancia a los
datos. Por ende no solo tendremos que eliminar las filas que representen
totales pero también aquellas filas que son las agrupaciones de otras
con el objeto de tener un conjunto \textbf{Tidy}.

En resumen, las columnas de delitos n1 y n5 no son necesarias y pueden
ser eliminadas sin problemas. Hemos averiguado que los delitos de N5 se
suman para los delitos de N4. Las columnas de delitos restantes serán
convertidas a factor. La columna edad será modificada para mayor
fidelidad al dato.

\subsubsection{Acondicionamiento y preparación de los
datos}\label{acondicionamiento-y-preparaciuxf3n-de-los-datos}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_delitos\_menores }\OtherTok{\textless{}{-}}\NormalTok{ delitos\_menores\_raw }\SpecialCharTok{\%\textgreater{}\%}
  \CommentTok{\# Retiramos las filas que se dividan/clasifiquen hasta el nivel 5}
  \FunctionTok{filter}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(delitos\_n5)) }\SpecialCharTok{\%\textgreater{}\%}
  
  \CommentTok{\# Selección de características/variables relevantes}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(delitos\_n1, delitos\_n5)) }\SpecialCharTok{\%\textgreater{}\%}

  \CommentTok{\# Renombramiento de las columnas}
  \FunctionTok{rename}\NormalTok{(}\AttributeTok{delito\_falta =}\NormalTok{ delitos\_n2,          }\CommentTok{\# Delito o Falta}
         \AttributeTok{clasi\_infrac =}\NormalTok{ delitos\_n3,          }\CommentTok{\# Primer nivel de clasifiación}
         \AttributeTok{sub\_clasi\_infrac =}\NormalTok{ delitos\_n4) }\SpecialCharTok{\%\textgreater{}\%}  \CommentTok{\# Segundo nivel de clasifiación}
  
  \CommentTok{\# Filtrado, retiramos las columnas que ya están pre{-}calculadas.}
  \CommentTok{\# Caso edad = "Total"}
  \CommentTok{\# Caso "nivel\_n1" era un "total" y los demás niveles de delito "NA"}
  \FunctionTok{filter}\NormalTok{(edad }\SpecialCharTok{!=} \StringTok{"Total"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(delito\_falta)) }\SpecialCharTok{\%\textgreater{}\%}
  
  \CommentTok{\# Reemplazo de valores}
  \FunctionTok{mutate}\NormalTok{(}
    \CommentTok{\# valores entendibles para "delito\_falta"}
    \AttributeTok{delito\_falta =} \FunctionTok{case\_when}\NormalTok{(delito\_falta }\SpecialCharTok{==} \StringTok{"A Delitos"} \SpecialCharTok{\textasciitilde{}} \StringTok{"delito"}\NormalTok{,}
\NormalTok{                             delito\_falta }\SpecialCharTok{==} \StringTok{"B Faltas"} \SpecialCharTok{\textasciitilde{}} \StringTok{"falta"}\NormalTok{),}
    \CommentTok{\# Eliminamos " años" y pasamos a numérico}
    \AttributeTok{edad =} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{substring}\NormalTok{(edad, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  
  \CommentTok{\# Convertimos a factores}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{delito\_falta =} \FunctionTok{as.factor}\NormalTok{(delito\_falta),}
    \AttributeTok{clasi\_infrac =} \FunctionTok{as.factor}\NormalTok{(clasi\_infrac),}
    \AttributeTok{sub\_clasi\_infrac =} \FunctionTok{as.factor}\NormalTok{(sub\_clasi\_infrac)}
\NormalTok{  )}

\CommentTok{\# WIP. Eliminacion aquellas columnas que tienen subclasisifaciones.}
\end{Highlighting}
\end{Shaded}

\subsubsection{Validación datos
acondicionados}\label{validaciuxf3n-datos-acondicionados}

Para validar que los datos se han cargado correctamente vamos a sacar
las columnas totales precaculadas y compararlas con

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Obtener los totales}
\NormalTok{df\_totales }\OtherTok{\textless{}{-}}\NormalTok{ delitos\_menores\_raw }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(edad }\SpecialCharTok{==} \StringTok{"Total"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{Análisis}\label{anuxe1lisis}

\subsection{Análisis de las
variables}\label{anuxe1lisis-de-las-variables}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# WIP:}
\CommentTok{\#   {-} Análisis de las variables (individualmente, explicación de los datos,}
\CommentTok{\#                                estadísticos.) (CARLOS)}
\CommentTok{\#   {-} Análisis de las variables (relaciones) (JOAN)}
\CommentTok{\# }
\CommentTok{\#}
\CommentTok{\# {-} NOTA: Se debe hacer uso de una "Visualización temprana (exploratoria)"}
\CommentTok{\#   de los datos. }
\CommentTok{\# {-} NOTA: Junto a la visualización se debe aportar una explicación.}
\end{Highlighting}
\end{Shaded}

\subsection{Análisis de `outliers', métodos de imputación aplicados y
análisis de datos
perdidos}\label{anuxe1lisis-de-outliers-muxe9todos-de-imputaciuxf3n-aplicados-y-anuxe1lisis-de-datos-perdidos}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# WIP:}
\CommentTok{\#   {-} Análisis de outliers, métodos de imputación y datos perdidos.}
\CommentTok{\# (si procede) (LUIS)}
\end{Highlighting}
\end{Shaded}

\subsection{Visualización
Explicatoria}\label{visualizaciuxf3n-explicatoria}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# WIP:}
\CommentTok{\#   {-} Visualización enfocada a los objetivos (encontrar una respuesta al problema). (TODOS)}
\CommentTok{\#}
\CommentTok{\# {-} NOTA: Junto a la visualización se debe aportar una explicación.}
\end{Highlighting}
\end{Shaded}

\section{Conclusiones}\label{conclusiones}

(TODOS) WIP: - Conclusiones finales. - Objetivos. - Proyecto. - NOTA:
Visualizaciones interactivas para finalizar/resumir, puede ser un buen
punto.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\vspace{6pt}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% optional

% Only for the journal Methods and Protocols:
% If you wish to submit a video article, please do so with any other supplementary material.
% \supplementary{The following supporting information can be downloaded at: \linksupplementary{s1}, Figure S1: title; Table S1: title; Video S1: title. A supporting video article is available at doi: link.}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\authorcontributions{WIP. En que hemos contribuido cada uno.}







%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Optional

%% Only for journal Encyclopedia


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Optional
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{adjustwidth}{-\extralength}{0cm}

%\printendnotes[custom] % Un-comment to print a list of endnotes



% If authors have biography, please use the format below
%\section*{Short Biography of Authors}
%\bio
%{\raisebox{-0.35cm}{\includegraphics[width=3.5cm,height=5.3cm,clip,keepaspectratio]{Definitions/author1.pdf}}}
%{\textbf{Firstname Lastname} Biography of first author}
%
%\bio
%{\raisebox{-0.35cm}{\includegraphics[width=3.5cm,height=5.3cm,clip,keepaspectratio]{Definitions/author2.jpg}}}
%{\textbf{Firstname Lastname} Biography of second author}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% for journal Sci
%\reviewreports{\\
%Reviewer 1 comments and authors’ response\\
%Reviewer 2 comments and authors’ response\\
%Reviewer 3 comments and authors’ response
%}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\PublishersNote{}
\end{adjustwidth}


\end{document}
